### ISSUE TITLE
USWDS autoprefixer requirements

### ISSUE THREAD

**Issue by aCyborg** [forumone/gesso-uswds#169] opened 2022-03-17 15:59 UTC
I'm using GUS on one of my projects and I noticed that the icons were showing up incorrectly for USWDS components:
<img width="330" alt="Screen Shot 2022-03-17 at 10 53 04 AM" src="https://user-images.githubusercontent.com/4439057/158840073-3bec4027-c925-4e7b-8e23-eb4ba0403e94.png">

I tracked it down to [an issue in USWDS](https://github.com/uswds/uswds/issues/4478) that notes that autoprefixer is a compilation requirement.

I noticed that `USWDS-compile` is being included in the package.json and I can see in my compiled CSS that there are some prefixes. It is unclear to me where the configuration is set and whether it is using the USWDS-compile package to do so or something else.

I may be able to implement this, but some direction on where to start would be appreciated as I am new to webpack.

**Comment by coreylafferty** [comment] 2022-03-18 19:30
Thanks for pointing this out and researching the root cause @aCyborg!  I just merged in a PR (#170) and put out a new release (5.0.9) which should address this issue. Let me know if it works for you.

**Comment by aCyborg** [comment] 2022-03-18 20:37
Thanks, @coreylafferty. I just tested the new release's updates in my project and the icon issue has been resolved 🥳

**Closed as completed** 2022-03-18 20:55 UTC
